
package Repository;

import java.sql.Connection;
import java.sql.SQLException;

import domain.Car;
import domain.Customer;
import domain.IHaveId;
import mapers.ResultSetMapper;

public class CustomerRepository  extends RepositoryBase {

	Connection connection;
	
	private String createTableSql;
	
	private String insertSql;
	private String updateSql;
	private String deleteSql;
	private String selectAllSql;
	public CustomerRepository(Connection connection, ResultSetMapper mapper) throws SQLException{
		super(connection, mapper);

		
	}
	
	protected void Init()
	{
		createTableSql = "CREATE TABLE customers("
				+ "id INT GENERATED BY DEFAULT AS IDENTITY,"
				+ "name VARCHAR(20),"
				+ "adress VARCHAR(20),"
				+ "phone VARCHAR(20),"
				+ ")";

		insertSql = "INSERT INTO customers(name,adress,phone) VALUES (?,?,?)";
		updateSql = "UPDATE customers SET (name,adress,phone) = (?,?,?) WHERE id=?";
		deleteSql = "DELETE FROM customers WHERE id=?";
		selectAllSql = "SELECT * FROM customers";
	}
	
	protected void setupInsert(IHaveId customer) throws SQLException {
		insert.setString(1, ((Customer) customer).getName());
		insert.setString(2, ((Customer) customer).getAdress());
		insert.setString(3, ((Customer) customer).getPhone());
	}
	
	protected void setupUpdate(IHaveId customer) throws SQLException {
		update.setString(1, ((Customer) customer).getName());
		update.setString(2, ((Customer) customer).getAdress());
		update.setString(3, ((Customer) customer).getPhone());
		update.setInt(4, ((Customer) customer).getId());
	}
	
	
	@Override
	protected String selectAllSql() {
		return selectAllSql;
	}
	
	@Override
	protected String deleteSql() {
		return deleteSql;
	}
	
	@Override
	protected String updateSql() {
		return updateSql;
	}
	
	@Override
	protected String insertSql() {
		return insertSql;
	}
	
	protected String tableName() {
		return "customers";
	}
	
	@Override
	protected String createTableSql() {
		return createTableSql;
	}
}